import {useEffect, useState} from 'react';
import {Copy, FlaskConical, HardDrive, Search} from 'lucide-react';
import {api} from '../api/client';
import type {NodeInfo} from '../types';

export function DemoLabPage() {
  const [nodes, setNodes] = useState<NodeInfo[]>([]); const [hash, setHash] = useState(''); const [node, setNode] = useState('node-1'); const [out, setOut] = useState('Ready.');
  const load = () => api<NodeInfo[]>('/cluster').then(setNodes);
  useEffect(() => { void load(); }, []);
  async function act(path: string, body?: Record<string, string>) { try { const result = await api<Record<string, unknown>>(path, {method: 'POST', body: body ? JSON.stringify(body) : undefined}); setOut(JSON.stringify(result, null, 2)); await load(); } catch (error) { setOut((error as Error).message); } }
  async function inspect() { try { setOut(JSON.stringify(await api<Record<string, unknown>>(`/placement/${hash}`), null, 2)); } catch (error) { setOut((error as Error).message); } }
  return <><div className="pageHead"><div><div className="eyebrow">CONTROLLED FAILURE INJECTION</div><h1>Demo lab</h1></div><span className="badge warn">ADMIN · DEMO MODE</span></div><div className="demoGrid"><section className="panel"><div className="panelTitle"><span>Node availability</span><HardDrive size={18}/></div><select value={node} onChange={e => setNode(e.target.value)}>{nodes.map(item => <option key={item.id}>{item.id}</option>)}</select><div className="actions"><button className="danger" onClick={() => void act('/demo/node/unavailable', {node_id: node})}>Simulate unavailable</button><button className="secondary" onClick={() => void act('/demo/node/restore', {node_id: node})}>Restore simulation</button></div></section><section className="panel"><div className="panelTitle"><span>Deduplication scenario</span><Copy size={18}/></div><p className="muted">Generate the same three-chunk file repeatedly. The response reports how many chunks were actually transferred.</p><button className="primary compact" onClick={() => void act('/demo/generate-duplicate')}>Generate duplicate example</button></section><section className="panel"><div className="panelTitle"><span>Placement inspector</span><Search size={18}/></div><input value={hash} onChange={e => setHash(e.target.value)} placeholder="64-char chunk SHA-256"/><button className="secondary" onClick={() => void inspect()}>Inspect placement</button></section><section className="panel"><div className="panelTitle"><span>Replica corruption</span><FlaskConical size={18}/></div><input value={hash} onChange={e => setHash(e.target.value)} placeholder="Chunk SHA-256"/><select value={node} onChange={e => setNode(e.target.value)}>{nodes.map(item => <option key={item.id}>{item.id}</option>)}</select><button className="danger" onClick={() => void act('/demo/corrupt', {chunk_hash: hash, node_id: node})}>Corrupt selected replica</button></section></div><section className="terminal"><div className="terminalHead">Lab output</div><pre>{out}</pre></section></>;
}
